### ISSUE TITLE
Prometheus stack name change might require changes in part 4

### ISSUE THREAD

**Issue by sasumaki** [kubernetes-hy/kubernetes-hy.github.io#22]
After this was merged https://github.com/kubernetes-hy/kubernetes-hy.github.io/commit/3a2c707cab89a9611848f58f42d9ab11bfae488f

some code examples in part 4 might cause some confusion because of them using the old prometheus operator.

I guess students are nohevia enough to survive this (?)

**Comment by Jakousa** [comment]
Part 4 is ähellys enough as it is so we should fix it.

**Comment by sasumaki** [comment]
all is fisked
