### ISSUE TITLE
part5 paragraph doesn't make sense at all.

### ISSUE THREAD

**Issue by sasumaki** [kubernetes-hy/kubernetes-hy.github.io#25]
"We’ve used a number of CRDs, Custom Resource Definitions, previously. They are a way to extend Kubernetes with our own Resources. So let us do just that and extend Kubernetes! There’s another option for API Aggregation but that’s left outside of the course."

The last sentence doesn't make sense at all if you're not familiar with the topics before diving into this.

**Comment by Jakousa** [comment]
https://github.com/kubernetes-hy/kubernetes-hy.github.io/commit/2751fe718913add14c1bd2c64dcfe3e428895a87
