### ISSUE TITLE
Broken link in Part 1 (First Deploy) regarding automatic completion

### ISSUE THREAD

**Issue by chanioxaris** [kubernetes-hy/kubernetes-hy.github.io#30]
In Part 1, First deploy section, there is a missing quote on href attribute, regarding the link to bash completion script tutorial.

I will submit a PR with a fix.

**Comment by chanioxaris** [comment]
[https://github.com/kubernetes-hy/kubernetes-hy.github.io/pull/31](PR)

**Comment by Jakousa** [comment]
Thanks!
