### ISSUE TITLE
Part 2, Chapter 2 : deleting pods doesn't update the deployment from the modified deployment.yaml file.

### ISSUE THREAD

**Issue by sahilrajput03** [kubernetes-hy/kubernetes-hy.github.io#80]
Towards the end of the material it taught that we must  delete the pod (with `kubectl delete po hashgenerator-dep-7b9b88f8bf-tnvfg`) so that changes we made in `deployment.yaml` file will be updated in the deployment and pod status respectively.

But it is not true coz to get update changes from the deployment.yaml file we must use `kubectl apply -f manifest/deployment.yaml` so that deployment gets updated. **Simply deleting the pod won't would reinitialize the pods but the configuration for deployment file will be used used as the file was before editing**.

PROOF: Here even after deleting the pods they reinitialize according to their behaviour.
![image](https://user-images.githubusercontent.com/31458531/160252707-5808f086-0cd8-43c7-87f6-83fe13b88262.png)
**PROVES: Updating the `deployment.yaml` file and deleting pods doesn't udpate the deployment from the file.**

***

Also, if I use the apply command the new pod created is in pending state as expected but the older deployment's pod reamins running. 

PROOF:
![image](https://user-images.githubusercontent.com/31458531/160252775-8a77a84b-d6fb-4181-b6ae-d1a090b87496.png)

***

If I delete the deployment followd by apply command i.e.,

![image](https://user-images.githubusercontent.com/31458531/160252850-21f858a6-d38f-452b-b350-606a8d03d1fa.png)

**it works as expected!**

So currently in material instead of:

```bash
$ kubectl delete po hashgenerator-dep-7b9b88f8bf-tnvfg
  pod "hashgenerator-dep-7b9b88f8bf-tnvfg" deleted

$ kubectl get po
  NAME                                 READY   STATUS    RESTARTS   AGE
  hashgenerator-dep-7b9b88f8bf-lvcv4   0/1     Pending   0          4s
```

it must be:

```bash
$ kubectl delete deploy hashgenerator-dep
  deployment.apps "hashgenerator-dep" deleted

$ kc apply -f manifests/deployment.yaml
  deployment.apps/hashgenerator-dep created

$ kubectl get po
  NAME                                 READY   STATUS    RESTARTS   AGE
  hashgenerator-dep-7b9b88f8bf-lvcv4   0/1     Pending   0          4s
```
.

**Comment by Jakousa** [comment]
Actually, the update means that nothing needs to be deleted. It will be correctly moved to the new node without deleting anything.
